version: '2'

volumes:
  mongodb-data:
   external: false
  
  elasticsearch-data:
   external: false
  
  graylog2-journal:
   external: false

services:
  mongodb:
    image: "mongo:3"
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db

  elasticsearch:
    image: "elasticsearch:2"
    restart: unless-stopped
    environment:
      ES_HEAP_SIZE: 1G
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    command: "elasticsearch -Des.cluster.name='graylog'"

  graylog2:
    image: "graylog2/server:2.2.3-1"
    environment:
      GRAYLOG_WEB_ENDPOINT_URI: "http://127.0.0.1:9000/api"
      GRAYLOG_PASSWORD_SECRET: aSshqyn5jXrPznQlKJXuBaddIcG4XeK5oBvBp0Ts5PPOJY4QTK2Q0TlzrivUFI2Fthnk9EGIIVTH7AWwNE0dPcZfCZw51vPg
      GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
    volumes:
      - graylog2-journal:/usr/share/graylog/data/journal
    links:
      - mongodb:mongo
      - elasticsearch:elasticsearch
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      - "9000:9000"
      - "12201-12209:12201-12209"
      - "12211-12219:12211-12219/udp"
