version: '3'

networks:
  log-net:
    driver: bridge

volumes:
  mongodb-data:
    external: false
  
  mongodb-config:
    external: false

  elasticsearch-data:
    external: false
  
  graylog2-data:
    external: false

services:
  mongodb:
    image: "mongo:3"
    restart: unless-stopped
    networks:
      log-net:
        aliases:
          - mongo
    volumes:
      - mongodb-data:/data/db
      - mongodb-config:/data/configdb

  elasticsearch:
    image: "elasticsearch:2"
    restart: unless-stopped
    environment:
      ES_HEAP_SIZE: 1G
    networks:
      log-net:
        aliases:
          - elasticsearch
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    command: "elasticsearch -Des.cluster.name='graylog'"

  graylog2:
    build: 
      context: .
    image: "groundhog2k/graylog2:latest"
    environment:
      GRAYLOG_WEB_ENDPOINT_URI: "http://127.0.0.1:9000/api"
      GRAYLOG_PASSWORD_SECRET: aSshqyn5jXrPznQlKJXuBaddIcG4XeK5oBvBp0Ts5PPOJY4QTK2Q0TlzrivUFI2Fthnk9EGIIVTH7AWwNE0dPcZfCZw51vPg
      GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      GRAYLOG_ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
      - log-net
    volumes:
      - graylog2-data:/usr/share/graylog/data
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      - "9000:9000"
      - "12201-12209:12201-12209"
      - "12211-12219:12211-12219/udp"

